### ISSUE TITLE
why the non-fork?

### ISSUE THREAD

**Issue by olilarkin** [sdatkinson/iPlug2-fork#1]
not sure why this has not been forked by clicking the fork button! 

this is a better way to maintain a fork, see the existing 250 or so:

https://github.com/iPlug2/iPlug2/forks

**Comment by sdatkinson** [comment]
I already have a fork of iPlug2 where I made the original NAM: https://github.com/sdatkinson/iPlug2

Trying to click "Fork" a second time doesn't work with this issue:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/12240186/235183852-73721066-6cd6-4f07-a7ea-a972234bd6c3.png">

Hence this.

I added this to ship https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/198. The plan is to shut this down once I have a chance to resolve the issues associated w/ updating the submodule to the latest iPlug2 (there are some breaking changes I need to figure out).
